name: Daily Batdongsan Crawler

on:
  schedule:
    - cron: '0 3 * * *'  # chạy lúc 3h sáng UTC (10h sáng VN)
  workflow_dispatch:       # cho phép chạy thủ công

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cài dependency
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium
          sudo apt-get update
          sudo apt-get install -y xvfb 
      - name: Test MySQL connection
        run: python test_mysql.py

      - name: Chạy script crawl + import (dùng Xvfb để giả lập trình duyệt thật)
        env:
          MYSQLHOST: ${{ secrets.MYSQLHOST }}
          MYSQLUSER: ${{ secrets.MYSQLUSER }}
          MYSQLPASSWORD: ${{ secrets.MYSQLPASSWORD }}
          MYSQLDATABASE: ${{ secrets.MYSQLDATABASE }}
          MYSQLPORT: ${{ secrets.MYSQLPORT }}

        run: |
          xvfb-run -a python bds.py 
          python importDBStaging.py
